# Ensemble modeling

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from pathlib import Path 
from fastai.vision import *
from fastai.tabular import *

In [3]:
defaults.device = torch.device('cpu')

In [4]:
path = %pwd
path = Path(f'{path}/../')

In [12]:
df = pd.read_csv(path/'csv/raw.csv')
val_data = pd.read_csv(path/'csv/validation.csv')['filename']

In [13]:
df = df[df['filename'].isin(val_data)]
df = df.sort_values(by='filename')
val_fns = df['filename']
df_val = df.drop(['filename', 'classes'], axis=1)

In [15]:
learn_wave = load_learner(path/'csv')

In [25]:
wave_pred = []
for idx, row in df.iterrows():
    pred = learn_wave.predict(row)
    wave_pred.append(pred) 

In [17]:
learn_melspecs = load_learner(path/'data')

In [20]:
melspecs_pred = []
for fn in val_fns:
    c = fn.split('_')[0]
    img_path = path/f'data/val_melspecs/{c}/{fn}.png'
    img = open_image(img_path)
    pred_class,pred_idx,outputs = learn_melspecs.predict(img)
    melspecs_pred.append([pred_class,pred_idx,outputs])

In [21]:
final_pred = []
for idx in range(len(melspecs_pred)): 
    final_pred.append((melspecs_pred[idx][2] + wave_pred[idx][2])/2)

In [22]:
final_pred

[tensor([0.7322, 0.0685, 0.1993]),
 tensor([0.7744, 0.0672, 0.1583]),
 tensor([0.7538, 0.0664, 0.1798]),
 tensor([0.7388, 0.0622, 0.1989]),
 tensor([0.1411, 0.4074, 0.4515]),
 tensor([0.6004, 0.1511, 0.2485]),
 tensor([0.5852, 0.3649, 0.0500]),
 tensor([0.5767, 0.3538, 0.0695]),
 tensor([0.5218, 0.3557, 0.1225]),
 tensor([0.0897, 0.8651, 0.0453]),
 tensor([0.0889, 0.8446, 0.0664]),
 tensor([0.0852, 0.8046, 0.1102]),
 tensor([0.1086, 0.8372, 0.0542]),
 tensor([0.0903, 0.8547, 0.0550]),
 tensor([0.0995, 0.7888, 0.1116]),
 tensor([0.1187, 0.7396, 0.1417]),
 tensor([0.0960, 0.8428, 0.0611]),
 tensor([0.0870, 0.8558, 0.0572]),
 tensor([0.0614, 0.3943, 0.5443]),
 tensor([0.5786, 0.1221, 0.2993]),
 tensor([0.2817, 0.0485, 0.6698]),
 tensor([0.5924, 0.3542, 0.0534]),
 tensor([0.2535, 0.0219, 0.7245]),
 tensor([0.4774, 0.0488, 0.4737]),
 tensor([0.1484, 0.1090, 0.7426]),
 tensor([0.5875, 0.1807, 0.2318]),
 tensor([0.5758, 0.2677, 0.1565])]